-- create tables
create table employees (
    empid                          number(30) GENERATED ALWAYS AS IDENTITY  constraint employees_empid_pk primary key not null,
    name                           varchar2(50) not null,
    salary                         number(30) not null default 0
)
;

-- load data
 
insert into employees (
    name
) values (
    'Gricelda Luebbers'
);

insert into employees (
    name
) values (
    'Dean Bollich'
);

insert into employees (
    name
) values (
    'Milo Manoni'
);

insert into employees (
    name
) values (
    'Laurice Karl'
);

insert into employees (
    name
) values (
    'August Rupel'
);

insert into employees (
    name
) values (
    'Salome Guisti'
);

insert into employees (
    name
) values (
    'Lovie Ritacco'
);

insert into employees (
    name
) values (
    'Chaya Greczkowski'
);

insert into employees (
    name
) values (
    'Twila Coolbeth'
);

insert into employees (
    name
) values (
    'Carlotta Achenbach'
);

insert into employees (
    name
) values (
    'Jeraldine Audet'
);

insert into employees (
    name
) values (
    'August Arouri'
);

insert into employees (
    name
) values (
    'Ward Stepney'
);

insert into employees (
    name
) values (
    'Ayana Barkhurst'
);

commit;
-- load data
 
-- Generated by Quick SQL Wednesday November 15, 2017  19:12:11
 
/*
employees /insert 14
      empid /nn num(30) /pk
      name /nn vc50 
      salary/nn num(30) 

view emp_v departments employees

# settings = { PK: "TRIG", language: "EN" }
*/
